version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "page-view-topic:1:1,page-view-enriched-topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  customer-app:
    image: customer-app
    environment:
      REDIS_HOST: redis
    ports:
        - "8080:8080"
    depends_on:
        - redis      
