version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.13
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "page-view-topic:6:1,page-view-enriched-topic:6:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
