version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.13
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "page-view-topic:6:1,page-view-enriched-topic:6:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  customer-app:
    image: customer-app
    environment:
      REDIS_HOST: redis
    ports:
        - "8080"
    depends_on:
        - redis
  event-receiver:
    image: event-receiver
    environment: 
      KAFKA_SERVERS: kafka:9092
      CUSTOMER_APP_SERVER: customer-app:8080
      NUMBER_OF_CONSUMERS: 1
    depends_on:
        - kafka
        - customer-app        